import {
  IS_PRODUCTION,
  MONAD_ACL_ADMIN,
  MONAD_ACL_MANAGER,
  MONAD_ATOKEN_IMPL,
  MONAD_COLLECTOR,
  MONAD_CONFIG_ENGINE,
  MONAD_DEFAULT_INTEREST_RATE_STRATEGY,
  MONAD_EMISSION_MANAGER,
  MONAD_INCENTIVES_CONTROLLER,
  MONAD_K613_PROTOCOL_DATA_PROVIDER,
  MONAD_L2_ENCODER,
  MONAD_ORACLE,
  MONAD_POOL,
  MONAD_POOL_ADDRESSES_PROVIDER,
  MONAD_POOL_CONFIGURATOR,
  MONAD_REWARDS_DISTRIBUTION,
  MONAD_STAKING,
  MONAD_TREASURY,
  MONAD_UI_INCENTIVE_DATA_PROVIDER,
  MONAD_UI_POOL_DATA_PROVIDER,
  MONAD_VARIABLE_DEBT_IMPL,
  MONAD_WALLET_BALANCE_PROVIDER,
  MONAD_WETH_GATEWAY,
} from 'src/const/env';
import {
  ARBITRUM_SEPOLIA_AAVE_PROTOCOL_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_ACL_ADMIN,
  ARBITRUM_SEPOLIA_ACL_MANAGER,
  ARBITRUM_SEPOLIA_ATOKEN_IMPL,
  ARBITRUM_SEPOLIA_COLLECTOR,
  ARBITRUM_SEPOLIA_DEFAULT_INTEREST_RATE_STRATEGY,
  ARBITRUM_SEPOLIA_INCENTIVES_CONTROLLER,
  ARBITRUM_SEPOLIA_L2_ENCODER,
  ARBITRUM_SEPOLIA_ORACLE,
  ARBITRUM_SEPOLIA_POOL,
  ARBITRUM_SEPOLIA_POOL_ADDRESSES_PROVIDER,
  ARBITRUM_SEPOLIA_POOL_CONFIGURATOR,
  ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION,
  ARBITRUM_SEPOLIA_STAKING,
  ARBITRUM_SEPOLIA_TREASURY,
  ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_VARIABLE_DEBT_IMPL,
  ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER,
  ARBITRUM_SEPOLIA_WETH_GATEWAY,
} from 'src/const/testnet';

export type NetworkAddresses = {
  POOL_ADDRESSES_PROVIDER: string;
  POOL: string;
  POOL_CONFIGURATOR: string;
  ORACLE: string;
  ACL_MANAGER: string;
  ACL_ADMIN: string;
  PROTOCOL_DATA_PROVIDER: string;
  ATOKEN_IMPL: string;
  VARIABLE_DEBT_IMPL: string;
  TREASURY: string;
  INCENTIVES_CONTROLLER: string;
  DEFAULT_INTEREST_RATE_STRATEGY: string;
  CONFIG_ENGINE: string;
  EMISSION_MANAGER: string;
  WALLET_BALANCE_PROVIDER: string;
  UI_POOL_DATA_PROVIDER: string;
  UI_INCENTIVE_DATA_PROVIDER: string;
  WETH_GATEWAY: string;
  L2_ENCODER: string;
  COLLECTOR: string;
  STAKING: string;
  REWARDS_DISTRIBUTION: string;
  /** @deprecated используй `STAKING` */
  staking: string;
  /** @deprecated используй `REWARDS_DISTRIBUTION` */
  rewardsDistribution: string;
};

export const addresses_testnet: NetworkAddresses = {
  POOL_ADDRESSES_PROVIDER: ARBITRUM_SEPOLIA_POOL_ADDRESSES_PROVIDER,
  POOL: ARBITRUM_SEPOLIA_POOL,
  POOL_CONFIGURATOR: ARBITRUM_SEPOLIA_POOL_CONFIGURATOR,
  ORACLE: ARBITRUM_SEPOLIA_ORACLE,
  ACL_MANAGER: ARBITRUM_SEPOLIA_ACL_MANAGER,
  ACL_ADMIN: ARBITRUM_SEPOLIA_ACL_ADMIN,
  PROTOCOL_DATA_PROVIDER: ARBITRUM_SEPOLIA_AAVE_PROTOCOL_DATA_PROVIDER,
  ATOKEN_IMPL: ARBITRUM_SEPOLIA_ATOKEN_IMPL,
  VARIABLE_DEBT_IMPL: ARBITRUM_SEPOLIA_VARIABLE_DEBT_IMPL,
  TREASURY: ARBITRUM_SEPOLIA_TREASURY,
  INCENTIVES_CONTROLLER: ARBITRUM_SEPOLIA_INCENTIVES_CONTROLLER,
  DEFAULT_INTEREST_RATE_STRATEGY: ARBITRUM_SEPOLIA_DEFAULT_INTEREST_RATE_STRATEGY,
  CONFIG_ENGINE: '',
  EMISSION_MANAGER: '',
  WALLET_BALANCE_PROVIDER: ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER,
  UI_POOL_DATA_PROVIDER: ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER,
  UI_INCENTIVE_DATA_PROVIDER: ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  WETH_GATEWAY: ARBITRUM_SEPOLIA_WETH_GATEWAY,
  L2_ENCODER: ARBITRUM_SEPOLIA_L2_ENCODER,
  COLLECTOR: ARBITRUM_SEPOLIA_COLLECTOR,
  STAKING: ARBITRUM_SEPOLIA_STAKING,
  REWARDS_DISTRIBUTION: ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION,
  staking: ARBITRUM_SEPOLIA_STAKING,
  rewardsDistribution: ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION,
};

export const addresses_mainnet: NetworkAddresses = {
  POOL_ADDRESSES_PROVIDER: MONAD_POOL_ADDRESSES_PROVIDER,
  POOL: MONAD_POOL,
  POOL_CONFIGURATOR: MONAD_POOL_CONFIGURATOR,
  ORACLE: MONAD_ORACLE,
  ACL_MANAGER: MONAD_ACL_MANAGER,
  ACL_ADMIN: MONAD_ACL_ADMIN,
  PROTOCOL_DATA_PROVIDER: MONAD_K613_PROTOCOL_DATA_PROVIDER,
  ATOKEN_IMPL: MONAD_ATOKEN_IMPL,
  VARIABLE_DEBT_IMPL: MONAD_VARIABLE_DEBT_IMPL,
  TREASURY: MONAD_TREASURY,
  INCENTIVES_CONTROLLER: MONAD_INCENTIVES_CONTROLLER,
  DEFAULT_INTEREST_RATE_STRATEGY: MONAD_DEFAULT_INTEREST_RATE_STRATEGY,
  CONFIG_ENGINE: MONAD_CONFIG_ENGINE,
  EMISSION_MANAGER: MONAD_EMISSION_MANAGER,
  WALLET_BALANCE_PROVIDER: MONAD_WALLET_BALANCE_PROVIDER,
  UI_POOL_DATA_PROVIDER: MONAD_UI_POOL_DATA_PROVIDER,
  UI_INCENTIVE_DATA_PROVIDER: MONAD_UI_INCENTIVE_DATA_PROVIDER,
  WETH_GATEWAY: MONAD_WETH_GATEWAY,
  L2_ENCODER: MONAD_L2_ENCODER,
  COLLECTOR: MONAD_COLLECTOR,
  STAKING: MONAD_STAKING,
  REWARDS_DISTRIBUTION: MONAD_REWARDS_DISTRIBUTION,
  staking: MONAD_STAKING,
  rewardsDistribution: MONAD_REWARDS_DISTRIBUTION,
};

/**
 * Набор адресов для текущего окружения:
 * - NODE_ENV === 'production'  → mainnet (Monad, значения из env)
 * - NODE_ENV === 'development' → testnet (Arbitrum Sepolia, хардкод-константы)
 */
export const addresses: NetworkAddresses = IS_PRODUCTION ? addresses_mainnet : addresses_testnet;

export const addresses_arbitrum_sepolia = addresses_testnet;
