import { cleanEnv, str, url } from 'envalid';

const rawEnv = {
  API_BASEURL: process.env.NEXT_PUBLIC_API_BASEURL,
  SUBGRAPH_ARBITRUM_SEPOLIA_URL: process.env.NEXT_PUBLIC_SUBGRAPH_ARBITRUM_SEPOLIA_URL,
  ARBITRUM_SEPOLIA_STAKING: process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_STAKING,
  ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION,
  ARBITRUM_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER,
  ARBITRUM_SEPOLIA_LENDING_POOL: process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_LENDING_POOL,
  ARBITRUM_SEPOLIA_WETH_GATEWAY: process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_WETH_GATEWAY,
  ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER,
  ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_L2_ENCODER: process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_L2_ENCODER,
  ARBITRUM_SEPOLIA_COLLECTOR: process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_COLLECTOR,
  BASE_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER:
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER,
  BASE_SEPOLIA_LENDING_POOL: process.env.NEXT_PUBLIC_BASE_SEPOLIA_LENDING_POOL,
  BASE_SEPOLIA_WETH_GATEWAY: process.env.NEXT_PUBLIC_BASE_SEPOLIA_WETH_GATEWAY,
  BASE_SEPOLIA_WALLET_BALANCE_PROVIDER:
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_WALLET_BALANCE_PROVIDER,
  BASE_SEPOLIA_UI_POOL_DATA_PROVIDER: process.env.NEXT_PUBLIC_BASE_SEPOLIA_UI_POOL_DATA_PROVIDER,
  BASE_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER:
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  BASE_SEPOLIA_L2_ENCODER: process.env.NEXT_PUBLIC_BASE_SEPOLIA_L2_ENCODER,
  PROTO_FUJI_LENDING_POOL_ADDRESS_PROVIDER:
    process.env.NEXT_PUBLIC_PROTO_FUJI_LENDING_POOL_ADDRESS_PROVIDER,
  PROTO_FUJI_LENDING_POOL: process.env.NEXT_PUBLIC_PROTO_FUJI_LENDING_POOL,
  PROTO_FUJI_WETH_GATEWAY: process.env.NEXT_PUBLIC_PROTO_FUJI_WETH_GATEWAY,
  PROTO_FUJI_FAUCET: process.env.NEXT_PUBLIC_PROTO_FUJI_FAUCET,
  PROTO_FUJI_WALLET_BALANCE_PROVIDER: process.env.NEXT_PUBLIC_PROTO_FUJI_WALLET_BALANCE_PROVIDER,
  PROTO_FUJI_UI_POOL_DATA_PROVIDER: process.env.NEXT_PUBLIC_PROTO_FUJI_UI_POOL_DATA_PROVIDER,
  PROTO_FUJI_UI_INCENTIVE_DATA_PROVIDER:
    process.env.NEXT_PUBLIC_PROTO_FUJI_UI_INCENTIVE_DATA_PROVIDER,
};

const env = cleanEnv(rawEnv, {
  API_BASEURL: url(),
  SUBGRAPH_ARBITRUM_SEPOLIA_URL: url(),
  ARBITRUM_SEPOLIA_STAKING: str(),
  ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION: str(),
  ARBITRUM_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER: str(),
  ARBITRUM_SEPOLIA_LENDING_POOL: str(),
  ARBITRUM_SEPOLIA_WETH_GATEWAY: str(),
  ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER: str(),
  ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER: str(),
  ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER: str(),
  ARBITRUM_SEPOLIA_L2_ENCODER: str(),
  ARBITRUM_SEPOLIA_COLLECTOR: str(),
  BASE_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER: str(),
  BASE_SEPOLIA_LENDING_POOL: str(),
  BASE_SEPOLIA_WETH_GATEWAY: str(),
  BASE_SEPOLIA_WALLET_BALANCE_PROVIDER: str(),
  BASE_SEPOLIA_UI_POOL_DATA_PROVIDER: str(),
  BASE_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER: str(),
  BASE_SEPOLIA_L2_ENCODER: str(),
  PROTO_FUJI_LENDING_POOL_ADDRESS_PROVIDER: str(),
  PROTO_FUJI_LENDING_POOL: str(),
  PROTO_FUJI_WETH_GATEWAY: str(),
  PROTO_FUJI_FAUCET: str(),
  PROTO_FUJI_WALLET_BALANCE_PROVIDER: str(),
  PROTO_FUJI_UI_POOL_DATA_PROVIDER: str(),
  PROTO_FUJI_UI_INCENTIVE_DATA_PROVIDER: str(),
});

export const {
  API_BASEURL,
  SUBGRAPH_ARBITRUM_SEPOLIA_URL,
  ARBITRUM_SEPOLIA_STAKING,
  ARBITRUM_SEPOLIA_REWARDS_DISTRIBUTION,
  ARBITRUM_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER,
  ARBITRUM_SEPOLIA_LENDING_POOL,
  ARBITRUM_SEPOLIA_WETH_GATEWAY,
  ARBITRUM_SEPOLIA_WALLET_BALANCE_PROVIDER,
  ARBITRUM_SEPOLIA_UI_POOL_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  ARBITRUM_SEPOLIA_L2_ENCODER,
  ARBITRUM_SEPOLIA_COLLECTOR,
  BASE_SEPOLIA_LENDING_POOL_ADDRESS_PROVIDER,
  BASE_SEPOLIA_LENDING_POOL,
  BASE_SEPOLIA_WETH_GATEWAY,
  BASE_SEPOLIA_WALLET_BALANCE_PROVIDER,
  BASE_SEPOLIA_UI_POOL_DATA_PROVIDER,
  BASE_SEPOLIA_UI_INCENTIVE_DATA_PROVIDER,
  BASE_SEPOLIA_L2_ENCODER,
  PROTO_FUJI_LENDING_POOL_ADDRESS_PROVIDER,
  PROTO_FUJI_LENDING_POOL,
  PROTO_FUJI_WETH_GATEWAY,
  PROTO_FUJI_FAUCET,
  PROTO_FUJI_WALLET_BALANCE_PROVIDER,
  PROTO_FUJI_UI_POOL_DATA_PROVIDER,
  PROTO_FUJI_UI_INCENTIVE_DATA_PROVIDER,
} = env;
