import { cleanEnv, str, url } from 'envalid';

const rawEnv = {
  API_BASEURL: process.env.NEXT_PUBLIC_API_BASEURL,
  SUBGRAPH_ARBITRUM_SEPOLIA_URL: process.env.NEXT_PUBLIC_SUBGRAPH_ARBITRUM_SEPOLIA_URL,
  MONAD_POOL_ADDRESSES_PROVIDER: process.env.NEXT_PUBLIC_MONAD_POOL_ADDRESSES_PROVIDER,
  MONAD_POOL: process.env.NEXT_PUBLIC_MONAD_POOL,
  MONAD_POOL_CONFIGURATOR: process.env.NEXT_PUBLIC_MONAD_POOL_CONFIGURATOR,
  MONAD_ORACLE: process.env.NEXT_PUBLIC_MONAD_ORACLE,
  MONAD_ATOKEN_IMPL: process.env.NEXT_PUBLIC_MONAD_ATOKEN_IMPL,
  MONAD_VARIABLE_DEBT_IMPL: process.env.NEXT_PUBLIC_MONAD_VARIABLE_DEBT_IMPL,
  MONAD_TREASURY: process.env.NEXT_PUBLIC_MONAD_TREASURY,
  MONAD_INCENTIVES_CONTROLLER: process.env.NEXT_PUBLIC_MONAD_INCENTIVES_CONTROLLER,
  MONAD_DEFAULT_INTEREST_RATE_STRATEGY:
    process.env.NEXT_PUBLIC_MONAD_DEFAULT_INTEREST_RATE_STRATEGY,
  MONAD_CONFIG_ENGINE: process.env.NEXT_PUBLIC_MONAD_CONFIG_ENGINE,
  MONAD_ACL_MANAGER: process.env.NEXT_PUBLIC_MONAD_ACL_MANAGER,
  MONAD_EMISSION_MANAGER: process.env.NEXT_PUBLIC_MONAD_EMISSION_MANAGER,
  MONAD_K613_PROTOCOL_DATA_PROVIDER: process.env.NEXT_PUBLIC_MONAD_K613_PROTOCOL_DATA_PROVIDER,
};

const env = cleanEnv(rawEnv, {
  API_BASEURL: url({ default: '' }),
  SUBGRAPH_ARBITRUM_SEPOLIA_URL: url({ default: '' }),
  MONAD_POOL_ADDRESSES_PROVIDER: str(),
  MONAD_POOL: str(),
  MONAD_POOL_CONFIGURATOR: str(),
  MONAD_ORACLE: str(),
  MONAD_ATOKEN_IMPL: str(),
  MONAD_VARIABLE_DEBT_IMPL: str(),
  MONAD_TREASURY: str(),
  MONAD_INCENTIVES_CONTROLLER: str(),
  MONAD_DEFAULT_INTEREST_RATE_STRATEGY: str(),
  MONAD_CONFIG_ENGINE: str(),
  MONAD_ACL_MANAGER: str(),
  MONAD_EMISSION_MANAGER: str(),
  MONAD_K613_PROTOCOL_DATA_PROVIDER: str(),
});

export const {
  API_BASEURL,
  SUBGRAPH_ARBITRUM_SEPOLIA_URL,
  MONAD_POOL_ADDRESSES_PROVIDER,
  MONAD_POOL,
  MONAD_POOL_CONFIGURATOR,
  MONAD_ORACLE,
  MONAD_ATOKEN_IMPL,
  MONAD_VARIABLE_DEBT_IMPL,
  MONAD_TREASURY,
  MONAD_INCENTIVES_CONTROLLER,
  MONAD_DEFAULT_INTEREST_RATE_STRATEGY,
  MONAD_CONFIG_ENGINE,
  MONAD_ACL_MANAGER,
  MONAD_EMISSION_MANAGER,
  MONAD_K613_PROTOCOL_DATA_PROVIDER,
} = env;
